feat: added custom media support
nomasystems/nclient pull request #9
Opened 2023-09-29 21:28 UTC by albertocsouto

- Added support to indicate other content types in request body different than json

2023-10-02 07:55 UTC, KeatoonMask commented
Hi @albertocsouto 

we are not working on this repo more. We continued this project in the Inditex repo, see attached link. Are you still using this for any internal project or so? I'm not sure what to do with `nclient` right now, should we close it or maintain it?

https://github.com/inditex/mlb-httpclientios

2023-10-02 13:42 UTC, KeatoonMask requested changes
Rest of changes look good to me!

2023-10-02 13:42 UTC, KeatoonMask commented on Sources/NClient/Endpoint.swift
> +    func serializeBody(_ body: RequestBody, contentType: HTTP.MIMEType, into request: inout URLRequest) throws {}
Are we using the `serializeBody` from outside?  Or just from the `request` method?

In case of not being used from outside, it seems that we do not need to include the `contentType` parameter. So this is already a `Endpoint` property.

2023-10-03 09:29 UTC, albertocsouto commented on Sources/NClient/Endpoint.swift
> +    func serializeBody(_ body: RequestBody, contentType: HTTP.MIMEType, into request: inout URLRequest) throws {}
You're right, thanks!

2023-10-04 06:56 UTC, KeatoonMask approved these changes

2023-10-04 06:56 UTC, merged